### ISSUE TITLE
Alive ?

### ISSUE THREAD

**Issue by funivan** [FF-Remote-Control/FF-Remote-Control#16]
Hi. Project is great but it is alive?
What is license of this project?
Can i fork it, make fixes/features and publish it?

**Comment by nneonneo** [comment]
@pmorch @harikvpy I have fixed some of the outstanding issues in my fork: https://github.com/nneonneo/FF-Remote-Control. I would be happy to take over maintenance for this project. I think the major thing that I would need is access to the Mozilla plugin submission, so that I could e.g. submit updated xpis.

**Comment by nneonneo** [comment]
@pmorch If you're still around, I'd be happy to be the maintainer for the extension and the repository. It's fine if you just point the README to my repo, and give me access to the plugin submission system.

**Comment by nneonneo** [comment]
I have taken over maintenance of this project, so in a sense it can be said to be alive again :)
